### ISSUE TITLE
Stories are not displayed correctly in DocsPage

### ISSUE THREAD

**Issue by tgfischer** [semoal/themeprovider-storybook#26]
**Description**
If you install the `@storybook/addon-docs` addon, it adds an autogenerated DocsPage containing all of the stories. However, there are styles included with this addon that force the height of the container for each story to be `100vh`, which is undesired.

The issue is because of the `Background` component: https://github.com/semoal/themeprovider-storybook/blob/afd873f3e7e1d135ae408fe96c23cf1f78e55ef6/src/Background.tsx#L21

**Expected behavior**
I'd expect that this addon does not change any of the styles

**Screenshots**
![image](https://user-images.githubusercontent.com/6805571/73743807-673e9600-471d-11ea-8975-553fed969991.png)
![image](https://user-images.githubusercontent.com/6805571/73743833-7887a280-471d-11ea-8b4b-3b90a49b07cd.png)

**Comment by semoal** [comment]
I'll take a look as soon as possible mate.

Thanks for posting the issue.

**Comment by semoal** [comment]
Right now, I'm looking an alternative of how background color is handled, there are two serveral options:
1.  Only enable this background to the story panel, not the docs.
2. Enable both of them handled through Storybook internal theming api. (I have to investigate if it's possible)

I'll try to implement the option two, as soon as I get more knowledge about storybook internal theming.

**Comment by tgfischer** [comment]
Is it possible to use [`createGlobalStyles`](https://styled-components.com/docs/api#createglobalstyle) to do this? Something like that could also allow us to change other things, such as the font

**Comment by semoal** [comment]
Fixed in # [1.3.0](https://github.com/semoal/themeprovider-storybook/compare/v1.2.5...v1.3.0) (2020-02-05)


### Bug Fixes

* console warning fixed ([fd71494](https://github.com/semoal/themeprovider-storybook/commit/fd71494d8a2ce2d9cb1a88b5cc8d2693d45a2187))
* fixed stories are not displayed correctly in DocsPage ([9cdf279](https://github.com/semoal/themeprovider-storybook/commit/9cdf2793b994d02b54e8b5a4824932897be66a3b))
* fixed Storyshots are blank when using this addon ([4971f0b](https://github.com/semoal/themeprovider-storybook/commit/4971f0ba0958b58850efbcae76775ebabfe6c640))


### Features

* now, stores selected theme on local-storage ([aaa4593](https://github.com/semoal/themeprovider-storybook/commit/aaa459342a7dae84a23a04fb709aee0bb808cd96))
