### ISSUE TITLE
Storyshots are blank when using this addon

### ISSUE THREAD

**Issue by tgfischer** [semoal/themeprovider-storybook#28]
When you add the `@storybook/addon-storyshots`  addon, and update the storyshots they are all blank. I'm using `create-react-app`, so the command I'm using is 

```
react-scripts test --watchAll=false -u
```

But I'd assuming it would be the same outcome if I just used `jest`. Regular snapshot tests are not affected

The issue might be here: https://github.com/semoal/themeprovider-storybook/blob/afd873f3e7e1d135ae408fe96c23cf1f78e55ef6/src/ThemesProvider.tsx#L40

Apologies for all of the issues this morning, just adding this to our application since it is pretty close to what we need. Thank you for all of the quick replies! :)

**Comment by semoal** [comment]
Thanks for the good review mate.

I'll like your review a lot, it gives me a excuse to do a little refactor to the lib to match the future of storybook (6.0.0@next branch), i'll maintain the connection for legacy storybook. (4.x, 5.x)

**Comment by semoal** [comment]
Fixed in # [1.3.0](https://github.com/semoal/themeprovider-storybook/compare/v1.2.5...v1.3.0) (2020-02-05)


### Bug Fixes

* console warning fixed ([fd71494](https://github.com/semoal/themeprovider-storybook/commit/fd71494d8a2ce2d9cb1a88b5cc8d2693d45a2187))
* fixed stories are not displayed correctly in DocsPage ([9cdf279](https://github.com/semoal/themeprovider-storybook/commit/9cdf2793b994d02b54e8b5a4824932897be66a3b))
* fixed Storyshots are blank when using this addon ([4971f0b](https://github.com/semoal/themeprovider-storybook/commit/4971f0ba0958b58850efbcae76775ebabfe6c640))


### Features

* now, stores selected theme on local-storage ([aaa4593](https://github.com/semoal/themeprovider-storybook/commit/aaa459342a7dae84a23a04fb709aee0bb808cd96))
